version: "3.9"
services:
  api:
    build: ./backend
    image: acc-api:local
    env_file: .env
    volumes:
      - acc_data:/app/data
    expose:
      - "8000"
    restart: unless-stopped

  web:
    build: ./frontend
    image: acc-web:local
    environment:
      - NEXT_PUBLIC_API_BASE=/api
    depends_on: [api]
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    depends_on: [api, web]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  acc_data:
  caddy_data:
  caddy_config:
